language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install autopoint

before_script:
  - ./MakeMakefile

script:
  - ./configure --prefix=/opt/rrdtool-master
  - make
  - sudo make install
  - /opt/rrdtool-master/bin/rrdtool
  - /opt/rrdtool-master/share/rrdtool/examples/4charts.pl
