language: c

perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.8"

install: 
  - sudo apt-get install autopoint libdbi-dev tcl-dev lua5.1 liblua5.1-0-dev valgrind
  - sudo pip install cpp-coveralls --use-mirrors

before_script:
  - ./MakeMakefile

script:
  - ./configure --prefix=/opt/rrdtool-master --disable-ruby
  - make CFLAGS+="-g -O0 -fprofile-arcs -ftest-coverage" LDFLAGS+="-fprofile-arcs --coverage"
  - make check
  - make check TESTS_STYLE=valgrind
  - sudo make install
  - cd bindings/perl-shared && make test
  - /opt/rrdtool-master/bin/rrdtool
  - /opt/rrdtool-master/share/rrdtool/examples/4charts.pl

# after_success:
#  - ( cd src ; find -name '*.c' | xargs -n 1 gcov -a .libs ; find -name '*.c' | xargs -n 1 )
#  - coveralls --no-gcov --encoding latin1 --exclude tests --exclude bindings

